export const LURE_LIST_REQUEST = 'LURE_LIST_REQUEST'

export const LURE_LIST_SUCCESS = 'LURE_LIST_SUCCESS'

export const LURE_LIST_FAIL = 'LURE_LIST_FAIL'

export const LURE_DETAILS_REQUEST = 'LURE_DETAILS_REQUEST'

export const LURE_DETAILS_SUCCESS = 'LURE_DETAILS_SUCCESS'

export const LURE_DETAILS_FAIL = 'LURE_DETAILS_FAIL'
